### ISSUE TITLE
T91 and BSD200 are HR or LR images?

### ISSUE THREAD

**Issue by XU-Shi** [phoenix104104/LapSRN#11]
Firstly. thank you for your code and paper.
As a beginner, I don't know 291 images in the paper are input LR images or the ground truth HR images. But whatever they are, they need the corresponding HR/LR images when being trained. I downloaded the Training Datasets (86.2 MB) in the link(http://vllab.ucmerced.edu/wlai24/LapSRN/). In the folder, there are 291 images in T91 and BSD200 not 291*2 images.
Looking forward to the recovery of you or others. Thanks.

**Comment by ch135** [comment]
Excuse me, I also have this question. Has the problem been solve?

**Comment by phoenix104104** [comment]
We generate LR images on-the-fly in the [getBatch](https://github.com/phoenix104104/LapSRN/blob/master/getBatch_LapSRN.m) function.

**Comment by notknowmuch** [comment]
> Firstly. thank you for your code and paper. As a beginner, I don't know 291 images in the paper are input LR images or the ground truth HR images. But whatever they are, they need the corresponding HR/LR images when being trained. I downloaded the Training Datasets (86.2 MB) in the link(http://vllab.ucmerced.edu/wlai24/LapSRN/). In the folder, there are 291 images in T91 and BSD200 not 291*2 images. Looking forward to the recovery of you or others. Thanks.

Excuse me, do you still have access to the dataset now? I find the link became 404 not found.
![WechatIMG197](https://github.com/phoenix104104/LapSRN/assets/97647105/59ca0181-6068-4742-a15e-dbd28cda043c)
