### ISSUE TITLE
Some questions about the final images

### ISSUE THREAD

**Issue by YouWillLikeIt** [phoenix104104/LapSRN#16]
The model is trained on Y-channel of image, what should i do if i want to generate a RGB image  according 
 to Y-channel of an image ?
 Thank you!

**Comment by phoenix104104** [comment]
Check [here](https://github.com/phoenix104104/LapSRN/blob/master/SR_MSLapSRN.m#L33-L67)

**Comment by HansonnnCheung** [comment]
When you convert a single-channel image to a three-channel（RGB） image, the other two channels are from HR images except for the Y-channel. Is this wrong?
