### ISSUE TITLE
About the training dataset

### ISSUE THREAD

**Issue by thecryboy** [phoenix104104/LapSRN#18]
thanks for your code.As you mentioned in the paper,the training dataset is t91 and bsd 200.However,the dataset is t91+bsd200+g100...  So ,what is the result for your paper? Is is consist of General 100?

**Comment by nachifur** [comment]
I have the same problem and look forward to your reply.

**Comment by phoenix104104** [comment]
The results in our paper are using the training data from T91 + BSB200 only. You are welcome to use G100 for further study.
