### ISSUE TITLE
 what is the version of MatConvNet used in this code?

### ISSUE THREAD

**Issue by 201528014227051** [phoenix104104/LapSRN#3]
Thanks for code publicly!
I encountered a version problem that as follows:
 "No property `ignoreAverage` for a layer of type `dagnn.vllab_dag_loss`."
After searched in the internet, maybe caused by the different version of MatConvNet. So could u tell me what is the version of MatConvNet used in this code?

**Comment by 201528014227051** [comment]
I miss the link in the repository, After downloaded the matconvnet from the link, the error still appear...."No property ignoreAverage for a layer of type dagnn.vllab_dag_loss."

**Comment by phoenix104104** [comment]
1. git clone --recursive https://github.com/phoenix104104/LapSRN.git
2. Did you copy vllab_dag_loss.m to matconvnet/matlab/+dagnn?
