### ISSUE TITLE
Error occurs when loading pre-trained_models

### ISSUE THREAD

**Issue by AaronHu13** [phoenix104104/LapSRN#4]
When I try to load the pre-trained_models, a error always occurs and I don't know how to fix it. I have checked that this is not caused by path but it seemed there are some problems in these .mat files or in the code.
![error](https://user-images.githubusercontent.com/17443068/30411445-8bff75c0-9943-11e7-998a-94b5e10bb03d.PNG)

**Comment by phoenix104104** [comment]
I never saw this error before. Did you use the same version of MatConvNet as my repository?
