### ISSUE TITLE
Error occurs when runnig demo_LapSRN.m

### ISSUE THREAD

**Issue by Jee-King** [phoenix104104/LapSRN#5]
It is successful to run install.m in matlab, but error occurs as follow:
**_>> demo_LapSRN
Load pretrained_models\LapSRN_x4.mat
error dagnn.Layer/load (line 200)
No property `ignoreAverage` for a layer of type `dagnn.vllab_dag_loss`.
error dagnn.DagNN.loadobj (line 28)
      block.load(struct(s.layers(l).block)) ;

error demo_LapSRN (line 33)
net = dagnn.DagNN.loadobj(net.net);_**
 
waiting your answer...

**Comment by phoenix104104** [comment]
You need to use the same or newer version of MatConvNet as my repository.
