### ISSUE TITLE
Python source code 

### ISSUE THREAD

**Issue by lchunleo** [phoenix104104/LapSRN#8]
Hi

Thanks for sharing. Unfortunately I don't have MATLAB. Wondering if it is possible to have Python version ? Thanks

**Comment by phoenix104104** [comment]
Check third-party implementation in [Tensorflow](https://github.com/zjuela/LapSRN-tensorflow) and [Pytorch](https://github.com/twtygqyy/pytorch-LapSRN)

**Comment by lchunleo** [comment]
Thank you. Will try it out.
